version: '2'

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  janus-gateway:
    image: mcroth/docker-janus:latest 
    container_name: janus-gateway
    volumes:
      - ./janus/etc/janus/:/opt/janus/etc/janus/
      - ./janus/janus.log:/var/log/janus.log
      - ./janus/certs/certificate.crt:/opt/janus/share/janus/certs/mycert.crt
      - ./janus/certs/privateKey.key:/opt/janus/share/janus/certs/mycert.key
    ports:
      - 8088:8088
      - 8089:8089
    networks:
      - back-tier
      - front-tier
